version: '3'

#Define services
services:

  #PostgreSQL Database for the application
  code-one-postgres:
    image: "postgres:15.1-alpine"
    container_name: code-one-postgres
    #Volume mounted for database for the storage
    volumes:
      - CodeOne-data:/var/lib/postgresql/15/main
    ports:
      - 5432:5432 # Forward the exposed port 5432 on the container to port 5432 on the host machine

    #Environment variable for DB name, user and password
    environment:
      - POSTGRES_DB=codeone1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=myPassword

  #Back-end Spring Boot Application
  codeone-app:
    #The docker file in scrum-app build the jar and provides the docker image with the following name.
    build: ./CatSearch
    container_name: codeone-app

    #Environment variables for Spring Boot Application.
    environment:
      - DB_SERVER=CodeOne-postgres
      - POSTGRES_DB=codeone1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=myPassword
    ports:
      - 8080:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine
    links:
      - code-one-postgres

  #Fron-end Angular Application
  code-front-ng:
    build: ./CodeFrontNg
    container_name: code-front-ng
    ports:
      - 4200:80
    links:
      - codeone-app

#Volumes for DB data
volumes:
  CodeOne-data:
